---
- name: Configure nginx configs
  ansible.builtin.template:
    src: "upstream.conf.j2"
    dest: "/etc/nginx/conf.d/upstream.conf"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - { src: upstream.conf.j2, path: conf.d/upstream.conf }

- name: Copy nginx configs
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "/etc/nginx/{{ item.path }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - { src: proxy.conf, path: default.d/proxy.conf }
    - { src: nginx.conf, path: nginx.conf }    
    
- name: Start nginx, if not started
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: true
