---
- name: Playbook with load balancer instructions
  hosts: lb
  become: yes
  roles:
    - load_balancer
  vars:
    worker_ips: "{{ groups.workers | map('extract', hostvars, 'ansible_host') }}"
