---
- name: Playbook with database instructions
  hosts: db_servers
  roles:
  - database

- name: Playbook with nfs instructions
  hosts: nfs_servers
  roles:
  - nfs

- name: Playbook with worker instructions
  hosts: workers
  roles:
  - gitbucket_worker
  vars:
    nfs_server: "{{ groups.nfs_servers.0 }}"
    mysql_server: "{{ groups.db_servers.0 }}"

- name: Playbook with load balancer instructions
  hosts: lb
  roles:
  - load_balancer
  vars:
    worker_ips: "{{ groups.workers }}"
