---
- hosts: db_servers
  roles:
  - database
  # vars:
  #   mysql_root_password: "{{ mysql_root_password_secret }}"
  #   mysql_gitbucket_password: "{{ mysql_gitbucket_password_secret }}"

- hosts: nfs_servers
  roles:
  - nfs

- hosts: workers
  roles:
  - gitbucket_worker
  vars:
    nfs_server: "{{ 'groups.nfs_servers.0' }}"
    mysql_server: "{{ 'groups.db_servers.0' }}"
    # mysql_gitbucket_password: "{{ mysql_gitbucket_password_secret }}"
