---
- name: Playbook with database instructions
  hosts: db_servers
  become: yes
  roles:
  - database

- name: Playbook with nfs instructions
  hosts: nfs_servers
  become: yes
  roles:
  - nfs

- name: Playbook with worker instructions
  hosts: workers
  become: yes
  roles:
  - gitbucket_worker
  vars:
    nfs_server: "{{ groups.nfs_servers.0 }}"
    mysql_server: "{{ groups.db_servers.0 }}"

- name: Restart tomcat sequentially
  hosts: workers
  become: yes
  serial: 1
  tasks:
  - name: Restart tomcat
    ansible.builtin.service:
      name: tomcat
      state: restarted
      enabled: true   

  - name: Wait for port 8080 to become open on the host, don't start checking for 20 seconds
    ansible.builtin.wait_for:
      host: 127.0.0.1
      port: 8080
      delay: 20

- name: Playbook with load balancer instructions
  hosts: lb
  become: yes
  roles:
  - load_balancer
  vars:
    worker_ips: "{{ groups.workers }}"
