---
- hosts: db_servers
  roles:
  - database
  vars_prompt:
    - name: mysql_root_password
      prompt: "Enter your MySQL root password"
      private: yes
    - name: mysql_gitbucket_password
      prompt: "Enter your MySQL gitdbuser password"
      private: yes      
  vars:
    mysql_server: "{{ 'inventory_hostname' }}"

- hosts: nfs_servers
  roles:
  - nfs
  vars:
    nfs_server: "{{ 'inventory_hostname' }}"

- hosts: workers
  roles:
  - gitbucket_worker
