---
- hosts: db_servers
  roles:
  - database

- hosts: nfs_servers
  roles:
  - nfs

- hosts: workers
  roles:
  - gitbucket_worker
  vars:
    nfs_server: "{{ groups.nfs_servers.0 }}"
    mysql_server: "{{ groups.db_servers.0 }}"
