---
- name: Playbook with worker instructions
  hosts: workers
  become: yes
  roles:
    - gitbucket_worker
  vars:
    nfs_server: "{{ hostvars.nfs_server1.ansible_host }}"
    mysql_server: "{{ hostvars.db_server1.ansible_host }}"

- name: Restart tomcat sequentially
  hosts: workers
  become: yes
  serial: 1
  tasks:
  - name: Restart tomcat
    ansible.builtin.service:
      name: tomcat
      state: restarted
      enabled: true   

  - name: Wait for port 8080 to become open on the host, don't start checking for 20 seconds
    ansible.builtin.wait_for:
      host: 127.0.0.1
      port: 8080
      delay: 20
