---
- name: Insert "JAVA_OPTS" configuration block in "/etc/tomcat/tomcat.conf"
  ansible.builtin.lineinfile:
    path: /etc/tomcat/tomcat.conf
    line: JAVA_OPTS="-Djava.security.egd=file:/dev/urandom -Dgitbucket.home=/gitbucket -Dgitbucket.disableCache=true -Dgitbucket.disableNewsFeed=true"
