---
- name: Mount an NFS volume
  ansible.posix.mount:
    src: "{{nfs_server}}:{{ item }}"
    path: "{{ item }}"
    state: mounted
    fstype: nfs
  with_items:
   - /gitbucket/data
   - /gitbucket/tmp
   - /gitbucket/repositories
   - /gitbucket/gist

- name: Configure database.conf in "/gitbucket/database.conf"
  ansible.builtin.template:
    src: "database.conf.j2"
    dest: "/gitbucket/database.conf"
    owner: "tomcat"
    group: "tomcat"
    mode: "0755"   

- name: Change file ownership, group and permissions for "/gitbucket"
  ansible.builtin.file:
    path: "/gitbucket"
    owner: "tomcat"
    group: "tomcat"
    mode: "0755"   
    recurse: yes 
