---
- name: Permit traffic in public zone for nfs and rpc-bind services
  ansible.posix.firewalld:
    zone: public
    service: "{{item}}"
    permanent: yes
    immediate: true
    state: enabled
  with_items:
    - nfs
    - nfs3  
    - mountd
    - rpc-bind

- name: Set SELinux boolean for nfs
  ansible.builtin.command: setsebool -P nfs_export_all_rw 1
