---
- name: Create "/gitbucket" directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
   - /gitbucket
   - /gitbucket/data
   - /gitbucket/tmp
   - /gitbucket/repositories
   - /gitbucket/gist   

- name: Configure exports in /etc/exports
  ansible.builtin.template:
    src: "exports.j2"
    dest: "/etc/exports"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - Reload nfs

- name: Export file systems in /etc/exports
  ansible.builtin.command: exportfs -rav
